FROM nginx:1.23.0-alpine


RUN mkdir -p /etc/letsencrypt
RUN mkdir -p /var/www/certbot

# COPY dockerfiles/prod/nginx/conf.d/ /etc/nginx/conf.d/
# COPY dockerfiles/prod/nginx/confing/ /etc/nginx/templates:rw,cached