version: "3.3"
   
services:
  app:
    build: .
    container_name: django_app
    command: sh -c "python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./core:/app
    environment:      
      - DEBUG=1      
    ports:
      - "8000:8000"
    